const navLinks = [
  { id: 1, name: "Portifólio" },
  { id: 2, name: "Contato" },
  { id: 3, name: "Projetos" },
];

const navIcons = [
  {
    id: 1,
    img: "/icons/wifi.svg",
  },
  {
    id: 2,
    img: "/icons/search.svg",
  },
  {
    id: 3,
    img: "/icons/user.svg",
  },
  {
    id: 4,
    img: "/icons/mode.svg",
  },
];

const dockApps = [
  {
    id: "finder",
    name: "Portfólio",
    icon: "finder.png",
    canOpen: true,
  },
  {
    id: "safari",
    name: "Certificados",
    icon: "safari.png",
    canOpen: true,
  },
  {
    id: "photos",
    name: "Curriculo",
    icon: "photos.png",
    canOpen: true,
  },
  {
    id: "contact",
    name: "Contato", 
    icon: "contact.png",
    canOpen: true,
  },
  {
    id: "terminal",
    name: "Skills",
    icon: "terminal.png",
    canOpen: true,
  },
  {
    id: "trash",
    name: "Lixeira",
    icon: "trash.png",
    canOpen: false,
  },
];

const INITIAL_Z_INDEX = 1000;

const WINDOW_CONFIG = {
  finder: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  contact: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  resume: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  safari: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  photos: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  terminal: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  txtfile: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  imgfile: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
};

const techStack = [
  {
    category: "Frontend",
    items: ["React.js", "Next.js", "TypeScript", "JavaScript"],
  },
  {
    category: "Estilização",
    items: ["Tailwind CSS", "BootStrap", "CSS"],
  },
  {
    category: "Backend",
    items: ["Node.js", "Express", "Prisma"],
  },
  {
    category: "Banco de Dados",
    items: ["PostgreSQL", "mySQL"],
  },
  {
    category: "Ferramentas",
    items: ["Git", "GitHub", "AWS"],
  },
];

const courses = [
  {
    id: 1,
    title: "ETS TOEIC Bridge",
    issuer: "TOEIC",
    category: "Inglês",
    date: "Mai de 2025",
    link: "https://drive.google.com/file/d/1SzGMQ6tUWYdbcBAS0ALI78ehvvwJnmdT/view?usp=sharing",
    imageURL: "/images/certificates/toeic-bridge.png",
  },
  {
    id: 2,
    title: "Inglês - Intermediate",
    issuer: "Fluency Academy",
    category: "Inglês",
    date: "Out de 2025",
    link: "https://drive.google.com/file/d/1vbd3b0qqIxuA4xeUbU1xTnocpJ6OM7ws/view?usp=sharing",
    imageURL: "/images/certificates/fluency-academy.png",
  },
  {
    id: 3,
    title: "Fundamentos de Data Science e Inteligência Artificial",
    issuer: "Data Science Academy",
    category: "Data Science",
    date: "Jul de 2025",
    link: "https://drive.google.com/file/d/18qUPabI1PvvypH-Y56dPxxwjqBCh5qB7/view?usp=sharing",
    imageURL: "/images/certificates/data-science-academy.png",
  },
  {
    id: 4,
    title: "Workshop do Figma ao Framer",
    issuer: "Framer Skills",
    category: "Design",
    date: "Mar de 2025",
    link: "https://drive.google.com/file/d/1xJY87ORdfCO2KPLVZIjYinlMusM-nHIh/view?usp=sharing",
    imageURL: "/images/certificates/framer-skills.png",
  },
  {
    id: 5,
    title: "Banco de Dados SQL",
    issuer: "OneBitCode",
    category: "Backend",
    date: "Jul de 2024",
    link: "https://drive.google.com/file/d/1RR67UT0TFkX6F2aYFEmWmlFCaqMLQXKx/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 6,
    title: "TailwindCSS",
    issuer: "OneBitCode",
    category: "Frontend",
    date: "Jul de 2024",
    link: "https://drive.google.com/file/d/1eaWgCFElL22vKiENhneesOaWD3bCVkEk/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 7,
    title: "UI e UX para programadores",
    issuer: "OneBitCode",
    category: "Design",
    date: "Jul de 2024",
    link: "https://drive.google.com/file/d/15ietjup3D10jntxokXaI7AzYKq4OZPN7/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 8,
    title: "Full Stack JavaScript",
    issuer: "OneBitCode",
    category: "Full Stack",
    date: "Jun de 2024",
    link: "https://drive.google.com/file/d/1-cJ_9s5EpupObGRmxrUCXjz3WlZYHBrZ/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 9,
    title: "EAD inspirado no Netflix",
    issuer: "OneBitCode",
    category: "Frontend",
    date: "Jun de 2024",
    link: "https://drive.google.com/file/d/1tde--s5TU43NvPQgcmbdROh9V9hArNsV/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 10,
    title: "Dominando o MongoDB",
    issuer: "OneBitCode",
    category: "Backend",
    date: "Abr de 2024",
    link: "https://drive.google.com/file/d/10F0Hb-8hcJUwbJrZWRDwGH6TXqImXkvx/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 11,
    title: "Next.JS (O Essencial)",
    issuer: "OneBitCode",
    category: "Frontend",
    date: "Mar de 2024",
    link: "https://drive.google.com/file/d/1JW2RTtHUf_GmjugoUUmEZ98XOs1zJTmG/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 12,
    title: "Banco de Dados SQL no NodeJS",
    issuer: "OneBitCode",
    category: "Backend",
    date: "Abr de 2024",
    link: "https://drive.google.com/file/d/1xTEYwzBHapPL3UzHEZ0-1Gn9xne_pANu/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 13,
    title: "Dominando o NodeJS",
    issuer: "OneBitCode",
    category: "Backend",
    date: "Abr de 2024",
    link: "https://drive.google.com/file/d/1Q_KqRtyx5BAt0d-bVdWJAI7Rl-XImtTs/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 14,
    title: "Fundamentos do React",
    issuer: "OneBitCode",
    category: "Frontend",
    date: "Mar de 2024",
    link: "https://drive.google.com/file/d/19wi8uEXnu3hR-IK26kClbAZ5jurlafFk/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 15,
    title: "Bootstrap",
    issuer: "OneBitCode",
    category: "Frontend",
    date: "Mar de 2024",
    link: "https://drive.google.com/file/d/1K2DUhjtRTP2d4E_orP3UZdqR5_5FVim9/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 16,
    title: "GIT e GitHub",
    issuer: "OneBitCode",
    category: "Ferramentas",
    date: "Jun de 2024",
    link: "https://drive.google.com/file/d/1KwULV4KgRnW6OMZaO12xsadQelANUj6e/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 17,
    title: "TypeScript",
    issuer: "OneBitCode",
    category: "Frontend",
    date: "Jan de 2024",
    link: "https://drive.google.com/file/d/1WQR2SUUbMOVExe1FIVmExJZTgpi067p3/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 18,
    title: "JavaScript I, II, III, IV, V, VI",
    issuer: "OneBitCode",
    category: "Frontend",
    date: "Jan de 2024",
    link: "https://drive.google.com/file/d/1p7Mvj0PqiagY_VPe9IJiKmPL3FAr4ddh/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 19,
    title: "CSS Moderno",
    issuer: "OneBitCode",
    category: "Frontend",
    date: "Fev de 2024",
    link: "https://drive.google.com/file/d/1IVabyybqU3h_EckUA7p7VfwueKh3xI96/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 20,
    title: "CSS3",
    issuer: "OneBitCode",
    category: "Frontend",
    date: "Dez de 2023",
    link: "https://drive.google.com/file/d/1Zjo_SalOPISL9LooYeNMd2v9XgvVIlP9/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
  {
    id: 21,
    title: "HTML5",
    issuer: "OneBitCode",
    category: "Frontend",
    date: "Dez de 2023",
    link: "https://drive.google.com/file/d/152ZP6gay2dZLpnK5aMSoy25dj_Cxevoe/view?usp=sharing",
    imageURL: "/images/certificates/onebitcode.png",
  },
];

export { navLinks, navIcons, dockApps, INITIAL_Z_INDEX, WINDOW_CONFIG, techStack, courses };
